export const REGULARIZACION_STEPS = [
  "Levantamiento",
  "Digitalización",
  "Pedir Documentos al Propietario si no hay",
  "Linea de Fabrica - IRM",
  "CD",
  "Checklist",
  "Ploteo de planos",
  "Cert. Gravamen",
  "Cédula Propietarios",
  "Escritura",
  "Impuest. Predial",
  "Memoria Fotográfica",
  "Formulario de Solicitud de Regularización",
  "Direccion Domiciliaria",
  "Otros",
  "Registro en la plataforma",
  "Numero de trámite",
  "Confirmación de asignación del tecnico municipal",
  "Membrete",
  "Hoja de Seguimeinto",
  "Carpeta Física Completa con Check List",
  "Ingreso de Carpeta Física",
  "Seguimiento en Municipio",
  "Subsanado",
  "Presentacion de Carpeta con firmas (4 Juegos)",
  "Seguimiento en municipio (3 días) y Retiro de orden de pago",
  "Pago del trámite (nos comunican para llamar al cliente)",
  "Retirar la carpeta",
  "Entregar al cliente una vez se confirme el pago del cliente"
];
